
services:
  db:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    container_name: teslo-db
    volumes:
      - ./postgres:/var/lib/postgresql/data