export enum Film {
  id = "id",
  title = "title",
  original_title = "original_title",
  original_title_romanised = "original_title_romanised",
  description = "description",
  director = "director",
  producer = "producer",
  release_date = "release_date",
  running_time = "running_time",
  rt_score = "rt_score",
  people = "people",
  species = "species",
  locations = "locations",
  vehicles = "vehicles",
  url = "url",
}